Main:
  Auto Plant Dropped Saplings: false
  Automatic Tree Destruction: true
  Destroy Only Blocks Above: false
  Force Break Default Radius: 10
  Force Grow Default Radius: 10
  Force Break Max Radius: 30
  Force Grow Max Radius: 30
  Ignore User Placed Blocks: false
  Language: en
  Sapling Replant: true
  Toggle Default: true
  Use mcMMO if Available: true
  Use Jobs if Available: true
  Use WorldGuard if Available: false
  Use Permissions: false
  Use Falling Blocks: false
Automatic Tree Destruction:
  Apply Full Tool Damage: true
  Auto Add To Inventory: false
  Cooldown (seconds): 0
  Delay (ticks): 0
  Forced Removal: false
  Increases Statistics: false
  Initial Delay: false
  Initial Delay (seconds): 10
  Remove Leaves: true
  Required Lore: ''
  Tree Types:
    Birch: true
    Jungle: true
    BigJungle: true
    BigSpruce: true
    Oak: true
    Spruce: true
    Brown Shroom: true
    Red Shroom: true
    Acacia: true
    Dark Oak: true
  When Sneaking: true
  When Not Sneaking: true
Block Statistics:
  Mine Block: false
  Pickup: false
Auto Plant Dropped Saplings:
  Chance (percent): 10
  Delay (seconds): 5
Leaf Decay:
  Fast Leaf Decay: true
Sapling Replant:
  Block all breaking of Saplings: false
  Bottom Block has to be Broken First: true
  Command Time Delay (Seconds): 30
  Delay until Sapling is replanted (seconds) (minimum 1 second): 1
  Enforce: false
  Replant When Tree Burns Down: true
  Time to Protect Sapling (Seconds): 0
  Time to Block Sapling Growth (Seconds): 0
  Tree Types to Replant:
    Birch: true
    Jungle: true
    BigJungle: true
    Oak: true
    Spruce: true
    Brown Shroom: true
    Red Shroom: true
    Acacia: true
    Dark Oak: true
Tools:
  Sapling Replant Require Tools: true
  Tree Destruction Require Tools: true
Worlds:
  Enable Per World: false
  Enabled Worlds:
  - world
  - world2
Placed Blocks:
  Handler Plugin Name: TreeAssist
  Handler Lookup Time: 86400
Modding:
  Disable Durability Fix: false
  Custom Tree Definitions:
  - - minecraft:birch_sapling
    - minecraft:birch_log
    - minecraft:birch_leaves
Debug: none
Version: 6.0
Trees:
- overworld
- nether
- mushroom